### ISSUE TITLE
Typo AirCnditioner

### ISSUE THREAD

**Issue by mkovatsc** [iot-schema-collab/iotschema#16] opened 2018-03-26 14:13 UTC
Should be fixed at http://iotschema.org/AirConditioner

**Comment by danbri** [comment] 2018-03-27 15:06
Near-duplicate of https://github.com/iot-schema-collab/iotschema/issues/16 which @danicic just fixed in Git, so I assume this will just propagate to the site next time someone updates it?

**Comment by danicic** [comment] 2018-03-27 15:12
The issue has been fixed. Thanks.

**Closed by danicic** 2018-03-27 15:12 UTC
